##게시글 등록
POST http://localhost:3000/api/groups/1/posts
Content-Type: application/json

{
	"nickname": "anonymous",
    "title":"제목1",
    "content":"내용1",
	"password": "1234",
	"imageUrl": "https://i.pinimg.com/736x/3b/e3/3d/3be33d221429fb01d3bbbf6779f4e141.jpg",
	"isPublic": false,
    "location":"대한민국",
    "moment":"2024-02-01" 
}
###

POST http://localhost:3000/api/groups/3/posts
Content-Type: application/json

{
	"nickname": "anonymous3",
    "title":"제목3",
    "content":"내용3",
	"password": "jtestnum",
	"imageUrl": "https://i.pinimg.com/736x/3b/e3/3d/3be33d221429fb01d3bbbf6779f4e141.jpg",
	"isPublic": true,
    "location":"일본",
    "moment":"2024-01-01" 
}
###
##게시글 수정
PUT http://localhost:3000/api/posts/4
Content-Type: application/json

{
	"nickname": "anonymous1-수정완료",
    "title":"제목2-수정완료",
    "content":"내용2-수정완료",
	"password": "jtestnum",
	"imageUrl": "https://i.pinimg.com/736x/3b/e3/3d/3be33d221429fb01d3bbbf6779f4e141.jpg",
	"isPublic": true,
    "location":"한국-수정완료",
    "moment":"2024-03-01" 
}
###

##게시글 수정
PUT http://localhost:3000/api/posts/5
Content-Type: application/json

{
	"nickname": "anonymous3-수정완료",
    "title":"제목3-수정완료",
    "content":"내용3-수정완료",
	"password": "jtestnum",
	"imageUrl": "https://i.pinimg.com/736x/3b/e3/3d/3be33d221429fb01d3bbbf6779f4e141.jpg",
	"isPublic": false,
    "location":"일본-수정완료",
    "moment":"2024-01-01" 
}

###

//게시글 삭제
DELETE http://localhost:3000/api/posts/2
Content-Type: application/json

{
    "postPassword":"1234"
}

###

//게시글 목록 조회
GET http://localhost:3000/api/groups/3/posts
Content-Type: application/json

###

GET http://localhost:3000/api/groups/3/posts?sortBy=likes
Content-Type: application/json

###

GET http://localhost:3000/api/groups/3/posts?sortBy=latest&page=1&pageSize=4&isPublic=true
Content-Type: application/json

###

GET http://localhost:3000/api/groups/3/posts?keyword=제
Content-Type: application/json

###

GET http://localhost:3000/api/groups/3/posts?keyword=3
Content-Type: application/json

###

//비밀번호 틀린 경우
DELETE http://localhost:3000/api/posts/5
Content-Type: application/json

{
    "postPassword":"jtestnum"
}

###

GET http://localhost:3000/api/posts/3
Content-Type: application/json


###
GET http://localhost:3000/api/posts/7
Content-Type: application/json


###
//게시글 조회 권한 확인

POST http://localhost:3000/api/posts/10/verify-password
Content-Type: application/json

{
    "password":"1234"
}

###
//게시글 조회 권한 확인 - 공개 그룹

POST http://localhost:3000/api/posts/7/verify-password
Content-Type: application/json

{
    "password":"1234"
}


###
//게시글 조회 권한 확인 - 비밀번호 틀림
POST http://localhost:3000/api/posts/11/verify-password
Content-Type: application/json

{
    "password":"1333"
}

###
//게시글 좋아요
POST http://localhost:3000/api/posts/3/like
Content-Type: application/json

###
//게시글 좋아요
POST http://localhost:3000/api/posts/3/like
Content-Type: application/json

###
//게시글 좋아요 - 2
POST http://localhost:3000/api/posts/7/like
Content-Type: application/json

//게시글 공개 여부 확인 - true
###
GET http://localhost:3000/api/posts/3/is-public
Content-Type: application/json

//게시글 공개 여부 확인 - false
###
GET http://localhost:3000/api/posts/10/is-public
Content-Type: application/json

